### ISSUE TITLE
你好 可以请教一下你用的数据集是哪个数据集吗

### ISSUE THREAD

**Issue by Masterkmp** [zhangwanyu2020/text_class#1]

**Comment by zhangwanyu2020** [comment]
如果需要，请留下你的邮箱

**Comment by yysirs** [comment]
1554987494@qq.com ,谢谢。

**Comment by Masterkmp** [comment]
你好，请问你是哪位？请详细描述一下你要问的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangwanyu2020/Text_class"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangwanyu2020/Text_class] 你好 可以请教一下你用的数据集是哪个数据集吗 (#1)





 
***@***.*** ,谢谢。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yysirs** [comment]
@Masterkmp 你好请问可以发下数据集吗？

**Comment by Masterkmp** [comment]
你好，就是用的新闻标题分类的数据集，你可以找找的，paddle上有。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangwanyu2020/Text_class"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月11日(星期六) 中午12:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangwanyu2020/Text_class] 你好 可以请教一下你用的数据集是哪个数据集吗 (#1)





 
@Masterkmp 你好请问可以发下数据集吗？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
